### ISSUE TITLE
Requirements Doc Rough Draft

### ISSUE THREAD

**Issue by car4p17** [SE181Group15/Chess#6]
Create a rough draft of the requirements document on [google drive](https://docs.google.com/document/d/14Q0NMs9RpRRUilGNH2j6Vt-_6_ZRRdjfZjigrZkRWb8/edit)

For now we need sections for everything in the sample as well as porting over the requirements we have in the project overview document.

The Sample Requirements Doc can be found here:
[Sample Requirements Document.pdf](https://github.com/SE181Group15/Chess/files/4100913/Sample.Requirements.Document.pdf)

**Comment by ghost** [comment]
Done and Submitted
