### ISSUE TITLE
Display Check and Checkmate

### ISSUE THREAD

**Issue by car4p17** [SE181Group15/Chess#7]
This is a Descendant of The add check issue #2 and will have to be done after that PR is added

In the GUIGamePrinter on line 163 there is this code:
```
 if (this.onGameOverCalled) {
            String message = winner.getName() + " Wins! ";
            g.setColor(Settings.highlightColor);
            g.fillRect(squareWidth * 8 / 2 - (int) (2.7 * radius) + offsetWidth, (squareHeight * 8 / 2) - radius, radius * message.length() / 2, (radius * 5) / 4);
            g.setFont(new Font("TimesRoman", Font.BOLD,  radius));
            g.setColor(winner);
            g.drawString(message, squareWidth * 8 / 2 - (int) (2.7 * radius) + offsetWidth, squareHeight * 8 / 2);
}
```
This is the current winner banner. We should update the message to include "Checkmate" in the form, "Checkmate, Black Wins!"

We will also need to add a copy of this which displays when the game is in check for a few seconds. In order to achieve this we will need to add a new function to the GameObserver interface, `onCheck(NamedColor inCheck)`
This will need to be propogated around all of the classes which implement GameObserver but the only one that needs to actually do anything in it right now is GUIGamePrinter. We will add a new boolean and function there like this
```
    @Override
    public void onCheck(NamedColor inCheck) {
        this.onCheckCalled= true;
        this.inCheck = inCheck;
        repaint();
    }
``
Finally we will need to update the ChessGame class to emit the onCheck event to all observers after a move is made after the onMove event is emited on line 51.

**Comment by ghost** [comment]
Updated the code to display check and checkmate. there is a time span of 4 seconds for displaying check.
